### PR TITLE
Hub client is nil if sentry isn't initialised

### PR DESCRIPTION
**Pull request by ovv**

### CODE REVIEW

**Comment by ovv** [comment]
@makasim ping

**Comment by makasim** [comment]
Does it make sense to use sentry hook when sentry is not initialized ? 

I think it would be better to document that sentry must be init before using sentry hook, maybe with an example. 

And if client is nil we can panic or something.

**Comment by ovv** [comment]
> if client is nil we can panic or something.

It is panicking currently but `logrus` as a `recover` in place when calling the hooks so it doesn't show

> Does it make sense to use sentry hook when sentry is not initialized ?

We setup the logger the same way for all environments and only enable sentry on production. We could do our logger differently but in any case it make sense to make the hook more robust and not panic if this happens.

**Comment by makasim** [comment]
> We setup the logger the same way for all environments and only enable sentry on production.
Make sense. Thanks for clarification.

**Comment by makasim** [comment]
https://github.com/makasim/sentryhook/tree/v0.4.0

**Comment by ovv** [comment]
Awesome thanks :+1:

**Pull request merged**
